apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Performing cleanup..."
        rm -rf /workspace/source/tmp || true


apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose-tests
spec:
  steps:
    - name: run-tests
      image: python:3.9
      script: |
        pip install nose
        nosetests
